### ISSUE TITLE
Kann mit Steam nicht einloggen.

### ISSUE THREAD

**Issue by BernhardOPT** [MorpheusXAUT/slotlist-frontend#140]
Login fehlgeschlagen - Irgendetwas ist fehlgeschlagen...
Diese Meldung kommt wenn ich über Steam einloggen will, seit Win 10 habe ich das Problem.
Gruß Bernhard

**Comment by b-mayr-1984** [comment]
Hallo Bernhard. Ich habe als ein "Bernhard" das gleiche Problem gehabt. Aber du kannst es umgehen in dem du dir vorübergehend in Steam einen anderen Nicknamen gibst. Ich konnte mich z.B. einloggen, als ich "Bernhard1984" als meinen Nick eingetragen hatte. Slotlist.info scheint ein Problem damit zu haben wenn Nutzernamen mehrfach vergeben wurden.

**Comment by MorpheusXAUT** [comment]
Hi.

Ich entschuldige mich erstmal für das lange Ignorieren der ganzen Issues hier, leider bin ich schon seit einigen Jahren nicht mehr wirklich in der ArmA-Szene involviert und habe nicht die Zeit gefunden, mich weiter damit zu beschäftigen.

@b-mayr-1984 jawohl - der Nickname ist aktuell in der Datenbank (warum auch immer 🤔) unique, sprich sobald es einen "Berhard" gibt, kann sich niemand anderes mit dem Steam-Nickname "Bernhard" einloggen. Ich bin mir leider nicht mehr ganz sicher, warum das damals unique geschalten wurde, hab aber auf die Schnelle keinen besonderen Grund dafür gefunden... 

Ich werde die Restriction mal aus der Datenbank entfernen - @BernhardOPT falls du es noch nicht aufgegeben oder schon anders geschafft hast, solltest du dich dann danach "normal" (ohne Änderung des Namens auf Steam" einloggen können. Bitte lasst mich wissen, falls es dadurch zu irgendwelchen komischen Zuständen oder anderen Fehler auf der Seite kommt - ich mach mal vorsichtshalber ein Backup der Datenbank davor 😛

**Comment by b-mayr-1984** [comment]
@MorpheusXAUT ok, gib einfach bescheid sobald wir es nochmal mit "Bernhard" probieren sollen. :-)

**Comment by MorpheusXAUT** [comment]
@b-mayr-1984 Change ist soeben durch, kannst es nochmal mit "Bernhard" probieren, danke!

**Comment by MorpheusXAUT** [comment]
@b-mayr-1984 ich geh mal davon aus, dass du "Bernhard1984" bist, richtig? Dann gibts deinen User in meiner DB aktuell sowieso schon, weil du dich einmal erfolgreich eingeloggt hast - der Nickname wechsel auf Steam hat dann keine Auswirkung mehr, außer wenn ich deinen User nochmal komplett löschen würde oder du einen anderen, noch nie eingeloggten Account mit dem Namen hast.

**Comment by b-mayr-1984** [comment]
@MorpheusXAUT Ja, der "Bernhard1984". Lösche ihn gerne nochmal, dann versuche ich es wieder mit "Bernhard" und gebe Rückmeldung.

**Comment by b-mayr-1984** [comment]
@MorpheusXAUT nevermind. Ich konnte meinen Account "Bernhard1984" selbst löschen. Danach konnte ich mich als "Bernhard" einloggen. Scheint also mit der deaktivierten Restriction zu funktionieren. :)

**Comment by MorpheusXAUT** [comment]
@b-mayr-1984 Wunderbar, danke fürs Testen und hier in den Issues erwähnen😄

**Comment by MorpheusXAUT** [comment]
Nach dem Test gestern mal geschlossen. Falls es noch zu Problemen kommen sollte, bitte einfach wieder aufmachen oder neues Ticket erstellen.
