### ISSUE TITLE
Everything takes ages to load

### ISSUE THREAD

**Issue by Maciekkub** [MorpheusXAUT/slotlist-frontend#141]
Whatever thing i click, be it account, registering for a slot, you name it takes from a couple of minutes to a couple of hours to load.
![pruf1](https://user-images.githubusercontent.com/30427887/99883793-f162d700-2c29-11eb-9b4d-94b017f585b4.png)
![pruf4](https://user-images.githubusercontent.com/30427887/99883794-f1fb6d80-2c29-11eb-8ae6-5f1e0169f54d.png)
![pruf3](https://user-images.githubusercontent.com/30427887/99883795-f1fb6d80-2c29-11eb-9f30-d8c45ec5dabc.png)
![pruf2](https://user-images.githubusercontent.com/30427887/99883796-f1fb6d80-2c29-11eb-868a-9724233b8b06.png)

**Comment by MorpheusXAUT** [comment]
Hi.

Unfortunately, there's been some performance issues over the last few months I haven't had time to look into as I currently have no spare time to invest into slotlist.info...
As the server running the service was sometimes hitting its limits, I've increased the resources allocated in a hope this will at least somewhat alleviate the loading time issues you're running into (feedback would be appreciated should the situation improve!).

Sadly, that's all of the assistance I can provide at the moment.

**Comment by Maciekkub** [comment]
Alright, well it did not help quite at all, although thanks for the effort. I have also discovered that i encounter these problems only on the Opera GX browser, because when i used Chrome there was almost no loading time

**Comment by MorpheusXAUT** [comment]
I'm glad to hear it's working well for you in a different browser, as I only use Chrome, all development/testing was done using Chrome only, although I've not heard of similar issues before (the number of Opera users I know is very limited though 😄).
Sorry I don't have time to investigate this any further.

**Comment by MorpheusXAUT** [comment]
Given there's not been any further complaints and load averages are looking okay now, I'll close this issue.
Feel free to re-open it in case you're running into further problems.
