### ISSUE TITLE
Support for Content DLC lableling

### ISSUE THREAD

**Issue by TheBorrow** [MorpheusXAUT/slotlist-frontend#143]
The new Content DLCs (e.g. GM or VN) are not available for selection in the „Reqired DLCs“ section of a mission.

As the CDLCs become more popular this would be a very useful feature.

**Comment by MorpheusXAUT** [comment]
Hi,

please see https://github.com/slotlist/slotlist-frontend/issues/138#issuecomment-874274999 - same issue as for the "regular" missing DLCs: unfortunately I do not have proper icons for those (and a lack of time and skill to create them myself), which is one of the reasons they haven't been added yet.

**If** I manage to create a local build to add the other DLCs at some point during this week, I'll try to add the creator DLCs as well. Is there a specific list you'd like to have added, or basically just everything that's listed on the [ArmA3 website](https://arma3.com) under DLCs + Creator DLCs?

**Comment by MorpheusXAUT** [comment]
Just released an update with the current list of DLCs included.
