### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by NiklasMerz** [MorpheusXAUT/slotlist-frontend#154]
I was thinking about doing PR to add the new DLCs? Are the maintainers available to review and deploy this? As my community (BF) is heavily using this tool I would like to help maintaining.

**Comment by Scarjit** [comment]
No, this is not really being maintained.
I would recommend creating a fork, and deploying it.

**Comment by NiklasMerz** [comment]
Thanks for the quick reply. This is a bit disappointing but the site is still working perfectly for us so we are happy nevertheless.

**Comment by MorpheusXAUT** [comment]
@NiklasMerz unfortunately, I don't have much time to dedicate to this project anymore and I've been out of the ArmA community for quite a while. Servers are still running as long as I can keep them up with the current effort and costs.
If you're (or someone else) is willing to take over the project and/or provide changes in the form of PRs, I'd be more than happy about that. I can try to find some time in between work and other obligations to merge PRs and deploy them, but I can't promise anything, unfortunately.
