### ISSUE TITLE
Logout after page refresh

### ISSUE THREAD

**Issue by Timi007** [MorpheusXAUT/slotlist-frontend#157]
About 2 days ago, some in our community and I noticed that we get logged out after a page refresh. Same on when leaving the page and returning.

Looking at the console, the following message is logged:
```
auth.js:254 No permissions in localStorage, clearing stored data
```

I can reproduce this in Chrome and Android Firefox. Same behavior and log message also in Incognito mode.

**Comment by NiklasMerz** [comment]
We also encountered the same problem for some weeks now.

**Comment by MorpheusXAUT** [comment]
Could you try again to see if the issue still persists?
I'm not sure _why_, but apparently switching back to the old image (before I set up the new stuff for @NiklasMerz ) somehow broke permission persistence... Switched back to the new image (which should be identical) and how it's working for me again...

_Magic_

**Comment by NiklasMerz** [comment]
Seems to be fixed somehow. The session persists for longer now.

**Comment by Timi007** [comment]
Can confirm. Thank you!
